<p><strong><?php _e('Authorize.net Accept', 'event_espresso'); ?></strong></p>
<p>
    <?php _e('Adjust the settings for the Authorize.net Accept payment gateway.', 'event_espresso'); ?>
</p>
<p><strong><?php _e('Authorize.net Accept Settings', 'event_espresso'); ?></strong></p>
<ul>
    <li>
        <strong><?php _e('Authorize.net Transaction Key', 'event_espresso'); ?></strong><br />
        <?php _e('The cryptographic key used in the HMAC calculation is the merchant’s unique Transaction Key, which is a 16-character value generated by the payment gateway. The merchant obtains this value from the Merchant Interface.',
            'event_espresso'); ?>
    </li>
    <li>
        <strong><?php _e('Authorize.net API login ID', 'event_espresso'); ?></strong><br />
<?php _e('The merchant API login ID is provided in the Merchant Interface and must be stored securely.',
    'event_espresso'); ?>
    </li>
    <li>
        <strong><?php _e('Debug Mode', 'event_espresso'); ?></strong><br />
<?php _e('Transactions will be submitted to the Authorize.net sandbox environment. Although this is a sandbox environment, its behavior mimics the live payment gateway.',
    'event_espresso'); ?>
    </li>
    <li>
        <strong><?php _e('Button Image URL', 'event_espresso'); ?></strong><br />
<?php _e('Change the image that is used for this payment gateway.', 'event_espresso'); ?>
    </li>
    <li>
        <strong><?php printf(__('More information on %s how to find your API Login ID and Transaction Key. %s',
        'event_espresso'), '<a href="https://support.authorize.net/authkb/index?page=content&id=A405" target="_blank">',
    '</a>'); ?></strong>
    </li>
    <h2><?php esc_html_e('Important Setup Notes', 'event_espresso');?></h2>
    <p><?php printf(
            esc_html__('This integration can use the Authorize.net Transaction Details API for increased security. %1$sPlease enable the Authorize.net Transaction Details API for your account.%2$s', 'event_espresso'),
            '<a href="https://developer.authorize.net/api/reference/features/transaction_reporting.html" target="_blank">',
        '</a>'
        ); ?></p>
    <p><?php
        $urlparts  = parse_url(site_url());
        $domain = isset($urlparts ['host']) ? $urlparts['host'] : '';
        printf(
                esc_html__('Web browsers may fail to display the billing form if your website is not using HTTPS. %1$sPlease ensure you have a valid SSL certificate%2$s and that all content is being served over HTTPS.', 'event_espresso'),
                '<a href="https://www.sslshopper.com/ssl-checker.html#hostname=' . $domain . '" target="_blank">',
                '</a>'
        );?></p>
</ul>