<?php
namespace WRCInfrastructure\Services;

class CommonServices
{
  public static function getCurrentSite($post_id = null)
  {
    static $site = NULL;

    if( empty($site) ) {
      $current_post_id = null;
      if(empty($post_id)){
        global $wp_query;
        if(! is_object($wp_query)) {
          return;
        }
        if(empty($wp_query->post)) {
          $site = null;
          return $site;
        }

        $current_post_id = $wp_query->post->ID;
      } else {
        $current_post_id = $post_id;
      }
      $ancestors = get_ancestors($current_post_id, 'page', 'post_type');
      //Check # of ancestors to see if we are on the top page.
      if( count($ancestors) > 0 ) {
        $topAncestor = $ancestors[count($ancestors) - 1];
        $site = get_field('site', $topAncestor);
      }
      else if(is_page_template('page-news-template.php')){
        $site = get_field('site', $current_post_id);
      } else if(is_page_template('page-events.php') || is_post_type_archive('espresso_events') ){
        //for the 'Critical Pages' and Archive generated by Event Espresso, which are shared among all events 
          $site = NULL;
      } else if (is_singular('learning-library')) {
        $learning_lib_sites = get_field('attached_site', $current_post_id);
        if(!empty($learning_lib_sites)){
          $site = $learning_lib_sites[0];
        }
      } else{
        //default to first site in user permissions
        $permissions = build_user_permissions();
        $site = $permissions['sites'][0];
      }

      /**
      * @todo handle if a site is not set. Redirect somewhere sane. Or maybe
      * that should be handled elsewhere.
      **/
    }

    return $site;
  }
}
