<?php
/**
 * Template Name: Events (Critical Pages)
 * Used for "Critical Pages" generated by Event Espresso plugin (Registration / Checkout / Thank You / etc)
 * @package wrcgroup-secure
 */

get_header();

$permissions = build_user_permissions();
$site = get_current_site();
//var_dump($site);

  if ( have_posts() ):
		while ( have_posts() ) : the_post(); ?>


		<div class="page_container events-page">
			<div id="primary" class="content-area">

				<?php the_content(); ?>

			</div><!-- #primary -->
		</div>
	<?php
	endwhile;
endif;

get_footer();
